n1=int(input("ingrese el primer numero:\n"))
n2=int(input("ingrese el segundo numero:\n"))
n3=int(input("ingrese el tercer numero:\n"))
n4=int(input("ingrese el cuarto numero:\n"))
n5=int(input("ingrese el quinto numero:\n"))
n6=int(input("ingrese el sexto numero:\n"))
n7=int(input("ingrese el septimo numero:\n"))
n8=int(input("ingrese el octavo numero:\n"))
n9=int(input("ingrese el noveno numero:\n"))
n10=int(input("ingrese el decimo numero:\n"))
lista=[n1,n2,n3,n4,n5,n6,n7,n8,n9,n10]
print(lista)
print("El primer número almacenado en la lista es:", n1)
print("El ultimo numero ingresado almacenado en la lista es:", n10)
